spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
  datasource:
    name: library
    url: jdbc:mysql://139.9.127.88:3306/cmsystem?useUnicode=true&characterEncoding=utf8
    username: root
    password: nuaamuyun99
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  mail:
    host: smtp.163.com
    username: cmsystem@163.com
    password: 654321bm
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true

mybatis:
  mapper-locations: classpath:Mapper/*.xml
  type-aliases-package: site.cmsystem.admin.pojo
  configuration:
    map-underscore-to-camel-case: true

mail:
  fromMail:
    addr: cmsystem@163.com
